export type UserProfile = {
  id: string;
  username: string;
  name: string;
  lastname: string;
  fullName: string;
  gender: string;
  birthday: string;
  status: string;
  bio: string;
  phone: string;
  lineId: string;
  height: string;
  weight: string;
  profileImageKey: string;
  avatarUrl: string | null;
  relationShipStatus: string;
  isVerified?: boolean;
  verificationType?: "ADMIN" | "USER" | null;
  verifiedAt?: string | null;
  isAdmin?: boolean;
};
